#
#  Global parameters
#

paths:
  projectpath: /home/kl467102/thesis
  datadir: data
  resultsdir: results
  configdir: config
  envdir: env
  tmpdir: tmp
  srcdir: src
  shellsrcdir: src/sh
  pysrcdir: src/py
  snakemakesrcdir: src/snakemake

genome: # if the project uses a single genome assembly
  symbol: "dm6"
  chromosomes: "chr2L chr2R chr3L chr3R chr4 chrX chrY"
  fasta: "data/genome/D.melanogaster/dm6/ucsc/fasta/dm6.fa"
  chrom_sizes: "data/genome/D.melanogaster/dm6/ucsc/fasta/dm6.chrom.sizes"

#
#  More parameters here
#

